---
# tasks file to deploy awx

- user: name={{ ansible_user }} groups=docker,wheel
- name: Kill ssh connections to reload user with docker group.
  meta: reset_connection

- name: Clone latest AWX repo to host.
  git:
    repo: "{{ awx_repo }}"
    dest: "{{ awx_repo_dir }}"
    version: "{{ awx_version }}"
    force: true
    accept_hostkey: true
  become: false

- name: Replace pg_hostname if local db install selected.
  replace:
    path: "{{ awx_repo_dir }}/installer/inventory"
    regexp: "# pg_hostname=postgresql"
    replace: "pg_hostname={{ pg_hostname }}"
  when: awx_db_type == "local" or awx_db_type == "remote"
  become: false
  notify:
    - Restart postgres server.

- name: Run the AWX installation playbook.
  command: "ansible-playbook -i inventory install.yml"
  args:
    chdir: "{{ awx_repo_dir }}/installer"
  when: ansible_connection != "docker"
  become: false
